export default Object.freeze({
  SEARCH_REPOS: 'SEARCH_REPOS',
  SEARCH_REPOS_SUCCESS: 'SEARCH_REPOS_SUCCESS',
  SEARCH_REPOS_FAILURE: 'SEARCH_REPOS_FAILURE',
  
  SORT_REPOS_BY_NAME: 'SORT_REPOS_BY_NAME',
  SORT_REPOS_BY_STARS: 'SORT_REPOS_BY_STARS',
  SORT_REPOS_BY_FORKS: 'SORT_REPOS_BY_FORKS'
});